/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.flexibook.application;
import java.sql.Time;

import javax.swing.JOptionPane;

import java.sql.Date;

import ca.mcgill.ecse.flexibook.view.AppointmentPage2;
import ca.mcgill.ecse.flexibook.view.AppointmentCalendar;
import ca.mcgill.ecse.flexibook.view.FlexiBookView;
import ca.mcgill.ecse.flexibook.view.Login;
import ca.mcgill.ecse.flexibook.view.OwnerWelcomePage;
import ca.mcgill.ecse.flexibook.view.ServicePage;
import ca.mcgill.ecse.flexibook.view.SignUpPage;
import ca.mcgill.ecse.flexibook.view.UpdateAccountPage;
import ca.mcgill.ecse.flexibook.controller.FlexiBookController;
import ca.mcgill.ecse.flexibook.controller.InvalidInputException;
import ca.mcgill.ecse.flexibook.model.Appointment;
import ca.mcgill.ecse.flexibook.model.BookableService;
import ca.mcgill.ecse.flexibook.model.Business;
import ca.mcgill.ecse.flexibook.model.ComboItem;
import ca.mcgill.ecse.flexibook.model.Customer;
import ca.mcgill.ecse.flexibook.model.FlexiBook;
import ca.mcgill.ecse.flexibook.model.Owner;
import ca.mcgill.ecse.flexibook.model.Service;
import ca.mcgill.ecse.flexibook.model.ServiceCombo;
import ca.mcgill.ecse.flexibook.model.TimeSlot;
import ca.mcgill.ecse.flexibook.model.User;
import ca.mcgill.ecse.flexibook.persistence.FlexiBookPersistence;

public class FlexiBookApplication {

	private static FlexiBook flexibook = FlexiBookApplication.getFlexibook();
	private static Owner owner;
	private static User currentUser;
	private static Date sysDate;

	public static void main(String[] args) {
		// start UI
		
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
	
	}
	
	
	
	public static FlexiBook getFlexibook() {
		if (flexibook == null) {
			// load model
			flexibook = FlexiBookPersistence.load();
		}
		return flexibook;
	}

	public static User getCurrentUser() {
		return currentUser;
	}
	
	public static void setCurrentUser(User user) {
		currentUser = user;
	}
	

	
	public static void setSysDate(Date a) {
		sysDate = a;
	}
	public static Date getSysDate() {
		return sysDate;
	}

}
